spring.application.name=homepick

# Thymeleaf 캐시 끄기 (저장 후 F5 새로고침 시 즉시 반영)
spring.thymeleaf.cache=false

# 정적 리소스(CSS, JS) 캐시 끄기
spring.web.resources.cache.period=0

# DevTools 재시작 및 LiveReload
spring.devtools.restart.enabled=true
# LiveReload 서버 활성화
spring.devtools.livereload.enabled=true